### PR TITLE
feat(website): add DocSearch as recommended by docusaurus.

### PR DESCRIPTION
**Pull request by s-pace**
👋 team,

I am working on DocSearch. [We have an integration for Docusaurus](https://docusaurus.io/docs/en/search#enabling-the-search-bar). We thought it is a shame you can not also used this search that you can [find on reactjs for example](https://reactjs.org/).

This PR will add DocSearch to the documentation website. It will allow an user to have a learn-as-you-type experience by displaying results thanks to a dropdown in a live way.

Let me know if you need anything.

### CODE REVIEW

**Comment by s-pace** [comment]
Any help on this?

**Comment by s-pace** [comment]
Any help on this @danthe3rd ?

**Comment by danthe3rd** [comment]
Hi @s-pace 
Sorry for the delay, I just saw the PR. Will loop back with the team and come back to you
Thank you for the suggestion :)

**Comment by danthe3rd** [comment]
So we discussed with the team, and we're not exactly sure how to integrate that properly. Most likely we will have to involve legals - because this might provide user data to a third party, requiring us to ask for consent, or because we use a provided token.
At this point, we believe that the effort is not worth the impact, especially given the relatively low volume of visitors in this blog/website.
Thank you anyway for the proposition

**Comment by s-pace** [comment]
We are helping most of the Docusaurus users with the same issue. You can find some details here https://www.algolia.com/doc/faq/security-privacy/gdpr/

**Pull request closed without merging**
